- lib/deimos/kafka_source.rb
- spec/kafka_source_spec.rb
Just a quick change so that KafkaSource destroy callback skips the send_event workflow, as its not required for a simple "delete" payload
Fixes #39 
> Change KafkaSource destroy callback to immediately publish instead of using send_events

- CHANGELOG.md
- lib/deimos.rb
- lib/deimos/backends/test.rb
- lib/deimos/test_helpers.rb
- spec/producer_spec.rb
Add `:test` producer backend which replaces the existing TestHelpers functionality of writing messages to an in-memory hash.
> Add test backend for Deimos

- CHANGELOG.md
- lib/deimos/kafka_source.rb
- spec/kafka_source_spec.rb
Fixes bug in `KafkaSource` that crashes if some records exist upon import with the `:on_duplicate_key_update` option
```ruby
YourModel.import(<new_records>)
YourModel.import(<updated_records>, on_duplicate_key_update: %i(columns_to_update))
YourModel.import(<new_and_updated_records>, on_duplicate_key_update: %i(columns_to_update))
```
> GUILD-131: Do not crash if some records exist upon import with 'on_duplicate_key_update'

- CHANGELOG.md
- lib/deimos/utils/lag_reporter.rb
- spec/utils/lag_reporter_spec.rb
Fixes #4, introduces `partition_last_offsets` that is used to recalculate consumer lag on heartbeat.
Pending dev tests, updated unit tests
> Recalculate lag on heartbeat

- CHANGELOG.md
- lib/deimos/kafka_topic_info.rb
- lib/deimos/utils/db_producer.rb
- lib/generators/deimos/db_backend/templates/migration
- lib/generators/deimos/db_backend/templates/rails3_migration
- spec/kafka_topic_info_spec.rb
- spec/utils/db_producer_spec.rb
- Retry deleting messages without resending the batch if the delete fails (fixes #34)
- Delete messages in batches rather than all at once to cut down on the chance of a deadlock.
- Add `last_processed_at` to `kafka_topic_info` to ensure that wait metrics are accurate in cases where records get created with an old `created_at` time (e.g. for long-running transactions).
Tested in production with relatively heavy load and an old MySQL database.
> Copy DB producer fixes from fadmin

- CHANGELOG.md
- lib/deimos/instrumentation.rb
- spec/kafka_listener_spec.rb
Fixes #19 - Update `send_produce_error` to decode `failed_messages` with built-in decoder. 
Tested on a staging environment of fadmin. Metrics show up in datadog tracking when errors happen during the delivery of messages to kafka. i.e 
```
Failed to send all messages to multi.Flyers.FlyerDataResponse/2; attempting retry 1 of 10 after 5s
Failed to fetch metadata from kafka://kafka-stg.bootstrap.wishabi.net:9093: Connection error Errno::ETIMEDOUT: Connection timed out
```
> Update send_produce_error to decode failed_messages with built-in decoder. 

- CHANGELOG.md
- lib/deimos/utils/db_producer.rb
- spec/utils/db_producer_spec.rb
`compact_messages` now uses `uniq` instead of `uniq!` which was causing it to fail on batch of unique messages.
Fixes #75 
> GH-75: Handle batch of unique messages in compact_messages

- CHANGELOG.md
- README.md
- lib/deimos/producer.rb
- spec/producer_spec.rb
This change allows for a topic to be specified in the 'publish' and 'publish_list' methods of a producer. This will override the topic set in the producer configuration for said producer. The benefit is so that you may have 1 producer that produces to multiple topics.
No, this has not been tested outside of specs. This will be used/tested with the upcoming Workflow Execution System being built by the Content Platform team.
> CPFM-331. Add ability to specify topic in publish and publish list

- CHANGELOG.md
- lib/deimos/producer.rb
- spec/producer_spec.rb
Changed the `publish_list` method in `lib/deimos/producer.rb` to raise error if the topic is blank.
Fixes #50 
> GH-50: Raise error if no topic is given while producing messages

- CHANGELOG.md
- lib/deimos/producer.rb
- spec/producer_spec.rb
Prepend topic_prefix to topic while encoding messages
Fixes #37 
> GH-37: Add topic prefix while encoding messages

- CHANGELOG.md
- docs/CONFIGURATION.md
- lib/deimos/config/configuration.rb
- lib/deimos/config/phobos_config.rb
- spec/config/configuration_spec.rb
Add "disabled" config field to consumers to allow disabling individual consumers without having to comment out their entries and possibly affecting unit tests.
> Consumer disabled config

- CHANGELOG.md
- Dockerfile
- README.md
- docs/INTEGRATION_TESTS.md
- lib/deimos/utils/db_producer.rb
- spec/utils/db_producer_spec.rb
- Do not resend already sent messages when splitting up batches in db_producer
- Uses a counter to keep track of the sent messages to kafka
- When accessing the `batch`, index directly into the `Array[Hash]` to the current location of the batch
- Adds a document called INTEGRATION_TESTS.md for running integration tests such as db_poller and db_producer/db backend
- Updated integration unit tests for db_producer
Fixes #24 
> GUILD-555: Don't resend messages when splitting up batches

- lib/deimos/backends/db.rb
- spec/backends/db_spec.rb
When using the key as the partition key in the database producer backend, encode as ~JSON~ YAML to avoid ActiveRecord quoting issues.
Fixes #95
> Use string-safe encoding for partition keys

- CHANGELOG.md
- lib/deimos/schema_backends/avro_schema_coercer.rb
- spec/schema_backends/avro_base_shared.rb
Adds logic to AvroSchemaCoercer to check the logical types of fields before coercing them. For `timestamp-millis` and `timestamp-micros` logical types, do not coerce them at all and let Avro's LogicalTypes modules handle it.
Fixes #97 
Added unit tests in `avro_based_shared.rb` to verify that the affected fields are not coerced.
> Fix coercion of timestamp-millis and -micros

- CHANGELOG.md
- lib/deimos/kafka_source.rb
- spec/kafka_source_spec.rb
The `kafka_producer` interface is outdated at this point and it's only there
for backwards compatibility. We're moving all the validation checks into the
`kafka_producers` and throwing a deprecation warning if the old interface is used.
Incidentally, this also takes care of the infinite loop we were seeing before when
no producer method was defined.
Fixes # (https://github.com/flipp-oss/deimos/issues/90)
> GUILD-569: Add validation for producer definition to KafkaSource module

- CHANGELOG.md
- lib/deimos/utils/db_poller.rb
…nsactions
The DB poller functionality forces a DB reconnect, even when there is an open transaction. This creates complications when running specs, as the specs run in a transaction that then gets forcibly closed. This change is to prevent that from happening. 
Fixes #110 (issue)
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] Running any spec using the DB poller on a new service would fail prior to this. They don't fail anymore.
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] I have …
> Cpfm 246 2

- CHANGELOG.md
- README.md
- lib/deimos/test_helpers.rb
- Deimos is not reset back to the default test config before each test now.
- A function has been added which can be called by clients in tests to manually reset Deimos back to test config.
- The same function can also be used to override settings while keeping defaults in place.
Fixes https://flippit.atlassian.net/browse/GUILD-619
Tested by calling this function in existing specs locally.
> GUILD-619: Test helpers don't automatically reset to test config

- CHANGELOG.md
- Gemfile.lock
- lib/deimos/schema_class/base.rb
- lib/deimos/schema_class/record.rb
- lib/deimos/utils/schema_class.rb
- spec/consumer_spec.rb
Fixes issue that was released with #122 - `Deimos` namespace was used previously for generated Schema Classes. Updated to use the `Schema` namespace and updated rspecs that were previously missed.
Tested on applications that were not working with #122. Fixed on those apps.
> Fix for changing Deimos:: to Schema:: module namespace

- CHANGELOG.md
- Gemfile.lock
- lib/deimos/utils/schema_controller_mixin.rb
- lib/deimos/version.rb
- Fix bug where schema controller mixin was using the schema name to register and not the namespaced schema name.
> Fix for schema controller mixin

- docs/CONFIGURATION.md
The `CONFIGURATION.md` doc seems to have an outdated or incorrect configuration field.
It references a `schema.generated_schema_path`, but looking at the code and the README the correct name seems to be `schema.generated_class_path`
> Fix `schema.generated_class_path` configuration name

- CHANGELOG.md
- docs/CONFIGURATION.md
- lib/deimos/config/configuration.rb
- lib/deimos/config/phobos_config.rb
- lib/deimos/schema_backends/avro_schema_registry.rb
- spec/config/configuration_spec.rb
Add support for Confluent Cloud, by adding SASL authentication.
Fixes #133
This PR solves 2 authentication issues with Confluent Cloud:
1. Provide SASL authentication when connecting to a Confluent Cloud Kafka cluster
2. Provide  Basic authentication when connecting to a Confluent Cloud Schema Registry
The issue at the moment is that the latter change relies on a change in `avro_turf` that was [introduced here](https://github.com/dasch/avro_turf/pull/121), and only released as part of v1.3.0. However `deimos` currently depends on `avro_turf ~> 0.11`, and when I tried relaxing the dependency to allow for `avro_turf 1.x`, I got an error with the schema classes generator.
I managed to pinpoint the issue to a [breaking change](https://github.com/dasch/avro_turf/pull/111) that was released …
> Confluent Cloud support

- CHANGELOG.md
- bin/console
- lib/deimos/config/configuration.rb
This PR fixes an issue where the initialization of the 2 mock providers would cause unwanted logs to be sent to STDOUT.
This is because the default values for `metrics` and `tracer` currently call the `#initialize` method in both `Metrics::Mock` and `Tracing::Mock` while the Deimos class is loaded.
There's currently no way to avoid that, including specifying a custom value for these settings.
This PR also includes a new `bin/console` script which allows developers to load up an IRB console with the local `deimos` gem loaded. This is a pretty common script (it's autogenerated in new gems nowadays), useful for testing uncommitted changes. It's been added in this PR because it makes it really easy to see the problem.
Since this issue happens when the `Deimos` is first loaded, it wasn't …
> Fix metrics and tracing defaults

- lib/deimos.rb
- lib/deimos/utils/db_poller.rb
Fixes [an issue](https://github.com/flipp-oss/deimos/runs/7436367328?check_suite_focus=true#step:4:1418) with the new `exit_on_signal` config that is defined in the top-level module.
> Fix sigurd require by requiring the top-level module instead of individual classes.

- docs/CONFIGURATION.md
In Basic Configuration, "Tracer" is used where "Tracing" is meant.
Documentation typo.
Copied config entry as it was in the documentation got error, changed documentation to match what works.
I just deleted the checklist because none seem to apply to doc change only.
> Tracer should be Tracing

- CHANGELOG.md
- lib/deimos/utils/db_poller/state_based.rb
Change the detection methods for primary_key in state_based mode
Fixes # (issue)
Bug in DB updates according to primary_key detection
> State Based Mode: change the detection of primary_key

- CHANGELOG.md
- docs/CONFIGURATION.md
- lib/deimos/active_record_consume/batch_consumption.rb
- lib/deimos/active_record_consumer.rb
- lib/deimos/config/configuration.rb
- spec/active_record_consume/batch_consumption_spec.rb
- spec/config/configuration_spec.rb
When consuming many records it is possible to overwhelm the database based on the amount of records being upserted/removed. This change adds a new option `max_db_batch_size`, which can be used to limit the amount of transactions in a single database call.
> CHP-1000: Add option to limit database queries to a maximum size

- CHANGELOG.md
- lib/deimos/active_record_consume/batch_consumption.rb
- lib/deimos/active_record_consume/batch_record.rb
- spec/active_record_batch_consumer_association_spec.rb
- spec/active_record_batch_consumer_spec.rb
This bug was introduced with #186. We really should fix #174 as this was the reason the tests didn't pick this up.
> Fix bug with associations

- CHANGELOG.md
- lib/deimos/utils/db_poller/state_based.rb
- lib/deimos/utils/db_poller/time_based.rb
- spec/utils/db_poller_spec.rb
This is a bug in the DB poller which can be described as follows:
* Message X comes in at timestamp 2.
* LOTS of messages come in at timestamp 2.
* DB poller takes 5 timestamps to process, so it’s now timestamp 7 when all the timestamp 2 messages are processed.
* While processing a batch with message X, another process updates the updated_at timestamp for message X with timestamp 6.
* Deimos updates last_sent to be timestamp 7.
* All messages with timestamp 6 are missed.
This bug was introduced with [this PR](https://github.com/flipp-oss/deimos/pull/169) - the idea was to ensure a 60-second wait if there were no messages to process - instead, it made it so *every* set of batches would end up with a last_sent time of the current time, since the last batch in the set is always empty.
> Don't update last_sent to current time on every poll

- lib/deimos/kafka_message.rb
- lib/deimos/utils/db_producer.rb
- spec/utils/db_producer_spec.rb
`@logger.error(Deimos::KafkaMessage.decoded(messages))` in the rescue block fails to decode the message and causes wrong exception raised
This PR:
- fixes message decoding
- adds rescue block around decoding call to make sure if decode is misconfigured that does not interfere with original exception
Fixes #195
tests added
> #195 Fix buffer overflow exception handling

- CHANGELOG.md
- lib/deimos/active_record_consume/batch_consumption.rb
- lib/deimos/active_record_consume/batch_record.rb
- lib/deimos/active_record_consume/mass_updater.rb
- lib/deimos/active_record_consumer.rb
- lib/deimos/config/configuration.rb
- spec/active_record_batch_consumer_spec.rb
- spec/active_record_consume/mass_updater_spec.rb
- spec/config/configuration_spec.rb
1. Allow global and individual consumer batch id generator procs to be passed in for use in bulk imports
2. Allow global and individual consumer replace_associations configuration for use in bulk imports
Fixes # (issue)
> CCOL-2039: Global consumer configurations for replace_association & bulk_id_generation

- CHANGELOG.md
- lib/deimos/config/configuration.rb
- lib/deimos/instrumentation.rb
- lib/deimos/utils/db_poller/base.rb
- spec/utils/db_poller_spec.rb
Currently, when DB Poller is unable to publish messages because they're too large for the broker, the poller will retry forever. This might be "correct" if we need some kind of alert / manual fix for the data. But in most cases, we'll want to just log an error and metric and move on.
This PR adds a configuration so we can make that happen.
> Option to skip large messages on DB poller

- CHANGELOG.md
- lib/deimos/config/phobos_config.rb
- spec/config/configuration_spec.rb
Enable Deimos persistent connections setting for individual producers
> CCOL-2356: Enable producers.persistent_connections setting

- CHANGELOG.md
- docs/CONFIGURATION.md
- lib/deimos/active_record_consume/batch_consumption.rb
- lib/deimos/active_record_consume/mass_updater.rb
- lib/deimos/active_record_consumer.rb
- lib/deimos/config/configuration.rb
- spec/active_record_consume/mass_updater_spec.rb
- spec/config/configuration_spec.rb
Normal bulk consumption logic:
```Record class:
Widget:
has_one : detail
```
1. Record class records (Widget) are saved
2. Record class primary keys are filled from DB
3. Associated records (Details) are updated with foreign key from record class
Backfill consumption logic (this change)
```Record class:
FidgetWidget
belongs_to: widget
belong_to: fidget
```
Notes:
* Record class cannot be upserted first as foreign_keys `widget_id`, `fidget_id` are required
1. Associated records (Widget & Fidget) are created and linked to record class (FidgetWidget)
2. Associated records are saved
3. Primary keys (`widget_id`, `fidget_id`) of associated records are filled from DB
4. Foreign keys of record class are filled with newly saved primary keys of associated records
Please describe the tests that you …
> CCOL-2440: Add consumer configuration to save associated keys prior to saving primary record

- CHANGELOG.md
- docs/CONFIGURATION.md
- lib/deimos/config/configuration.rb
- lib/deimos/producer.rb
- spec/producer_spec.rb
Enabled the ability to configure `max_batch_size` on a per-producer level instead of hard-coded limit of 500. The global setting is still set to 500 by default.
Fixes [CCOL-2441](https://flippit.atlassian.net/browse/CCOL-2441)
Added specs
> CCOL-2441: Allow custom publishing batch size per producer

- CHANGELOG.md
- docs/CONFIGURATION.md
- lib/deimos/config/configuration.rb
- lib/deimos/kafka_source.rb
- spec/kafka_source_spec.rb
This adds a new configuration, `truncate_columns`. When turned on, there is a separate step that runs before sending a message via KafkaSource that truncates any values that are too long down to the limit set by the database.
This is because some databases (such as MySQL with a relaxed sql_mode) will auto-truncate values when they are saved to the database. If we don't do this step, since we are looking at the record *before* it is saved to the database, Kafka will get values that don't reflect what's actually saved in the database.
> Add truncate_columns configuration

- CHANGELOG.md
- lib/deimos/kafka_topic_info.rb
I want to rename table_name in Deimos::KafkaTopicInfo from 'kafka_topic_info' to 'kafka_topic_info_new'.
```ruby
Deimos::KafkaTopicInfo.class_eval do
self.table_name = 'kafka_topic_info_new'
end
```
I discovered this issue while doing so. This reference to plain string is the bug.
Fixes # (issue)
- Ran kafka_topic_info_spec locally
> Change reference to variable instead of plain string 'kafka_topic_info'

- CHANGELOG.md
- lib/deimos/metrics/minimal_datadog.rb
- lib/deimos/metrics/minimal_datadog_listener.rb
DataDog custom metrics can get expensive - this provides a listener that sends a much smaller set.
> Feature: Add MinimalDatadog metrics listener.

- CHANGELOG.md
- lib/deimos/backends/base.rb
- lib/deimos/logging.rb
- spec/producer_spec.rb
- spec/spec_helper.rb
- Fix: Do not force data to JSON when logging payloads. This allows log formatters to handle the payloads on their own (e.g. adding additional fields).
- Fix: Add topic to "Publishing Messages" log message.
> Fixes re logging
